<?php

namespace Database\Seeders;

use App\Models\SubCounty;
use Illuminate\Database\Seeder;

class SubCountySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subCounties = [
            // Mombasa County (1)
            ['county_id' => 1, 'constituency_name' => 'changamwe', 'ward' => 'port reitz', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'changamwe', 'ward' => 'kipevu', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'changamwe', 'ward' => 'airport', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'changamwe', 'ward' => 'changamwe', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'changamwe', 'ward' => 'chaani', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'jomvu', 'ward' => 'jomvu kuu', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'jomvu', 'ward' => 'miritini', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'jomvu', 'ward' => 'mikindani', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'mjambere', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'junda', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'bamburi', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'mwakirunge', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'mtopanga', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'magogoni', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'kisauni', 'ward' => 'shanzu', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'nyali', 'ward' => 'frere town', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'nyali', 'ward' => 'ziwa la ng\'ombe', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'nyali', 'ward' => 'mkomani', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'nyali', 'ward' => 'kongowea', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'nyali', 'ward' => 'kadzandani', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'likoni', 'ward' => 'mtongwe', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'likoni', 'ward' => 'shika adabu', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'likoni', 'ward' => 'bofu', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'likoni', 'ward' => 'likoni', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'likoni', 'ward' => 'timbwani', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'mvita', 'ward' => 'mji wa kale/makadara', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'mvita', 'ward' => 'tudor', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'mvita', 'ward' => 'tononoka', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'mvita', 'ward' => 'shimanzi/ganjoni', 'alias' => ''],
            ['county_id' => 1, 'constituency_name' => 'mvita', 'ward' => 'majengo', 'alias' => ''],
            
            // Kwale County (2)
            ['county_id' => 2, 'constituency_name' => 'msambweni', 'ward' => 'gombatobongwe', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'msambweni', 'ward' => 'ukunda', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'msambweni', 'ward' => 'kinondo', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'msambweni', 'ward' => 'ramisi', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'lungalunga', 'ward' => 'pongwekikoneni', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'lungalunga', 'ward' => 'dzombo', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'lungalunga', 'ward' => 'mwereni', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'lungalunga', 'ward' => 'vanga', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'matuga', 'ward' => 'tsimba golini', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'matuga', 'ward' => 'waa', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'matuga', 'ward' => 'tiwi', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'matuga', 'ward' => 'kubo south', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'matuga', 'ward' => 'mkongani', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'nadavaya', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'puma', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'kinango', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'mackinnon-road', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'chengoni/samburu', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'mwavumbo', 'alias' => ''],
            ['county_id' => 2, 'constituency_name' => 'kinango', 'ward' => 'kasemeni', 'alias' => ''],
            
            // Kilifi County (3)
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'tezo', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'sokoni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'kibarani', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'dabaso', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'matsangoni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'watamu', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi north', 'ward' => 'mnarani', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi south', 'ward' => 'junju', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi south', 'ward' => 'mwarakaya', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi south', 'ward' => 'shimo la tewa', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi south', 'ward' => 'chasimba', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kilifi south', 'ward' => 'mtepeni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kaloleni', 'ward' => 'mariakani', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kaloleni', 'ward' => 'kayafungo', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kaloleni', 'ward' => 'kaloleni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'kaloleni', 'ward' => 'mwanamwinga', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'rabai', 'ward' => 'mwawesa', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'rabai', 'ward' => 'ruruma', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'rabai', 'ward' => 'kambe/ribe', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'rabai', 'ward' => 'rabai/kisurutini', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'ganze', 'ward' => 'ganze', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'ganze', 'ward' => 'bamba', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'ganze', 'ward' => 'jaribuni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'ganze', 'ward' => 'sokoke', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'malindi', 'ward' => 'jilore', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'malindi', 'ward' => 'kakuyuni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'malindi', 'ward' => 'ganda', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'malindi', 'ward' => 'malindi town', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'malindi', 'ward' => 'shella', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'marafa', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'magarini', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'gongoni', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'adu', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'garashi', 'alias' => ''],
            ['county_id' => 3, 'constituency_name' => 'magarini', 'ward' => 'sabaki', 'alias' => ''],
            
            // Tana River County (4)
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'kipini east', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'garsen south', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'kipini west', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'garsen central', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'garsen west', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'garsen', 'ward' => 'garsen north', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'galole', 'ward' => 'kinakomba', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'galole', 'ward' => 'mikinduni', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'galole', 'ward' => 'chewani', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'galole', 'ward' => 'wayu', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'bura', 'ward' => 'chewele', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'bura', 'ward' => 'bura', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'bura', 'ward' => 'bangale', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'bura', 'ward' => 'sala', 'alias' => ''],
            ['county_id' => 4, 'constituency_name' => 'bura', 'ward' => 'madogo', 'alias' => ''],
            
            // Lamu County (5)
            ['county_id' => 5, 'constituency_name' => 'lamu east', 'ward' => 'faza', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu east', 'ward' => 'kiunga', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu east', 'ward' => 'basuba', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'shella', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'mkomani', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'hindi', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'mkunumbi', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'hongwe', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'witu', 'alias' => ''],
            ['county_id' => 5, 'constituency_name' => 'lamu west', 'ward' => 'bahari', 'alias' => ''],
            
            // Taita Taveta County (6)
            ['county_id' => 6, 'constituency_name' => 'taveta', 'ward' => 'chala', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'taveta', 'ward' => 'mahoo', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'taveta', 'ward' => 'bomeni', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'taveta', 'ward' => 'mboghoni', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'taveta', 'ward' => 'mata', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'wundanyi', 'ward' => 'wundanyi/mbale', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'wundanyi', 'ward' => 'werugha', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'wundanyi', 'ward' => 'wumingu/kishushe', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'wundanyi', 'ward' => 'mwanda/mgange', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'mwatate', 'ward' => 'rong\'e', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'mwatate', 'ward' => 'mwatate', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'mwatate', 'ward' => 'bura', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'mwatate', 'ward' => 'chawia', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'mwatate', 'ward' => 'wusi/kishamba', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'mbololo', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'sagalla', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'kaloleni', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'marungu', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'kasigau', 'alias' => ''],
            ['county_id' => 6, 'constituency_name' => 'voi', 'ward' => 'ngolia', 'alias' => ''],
            
            // Garissa County (7)
            ['county_id' => 7, 'constituency_name' => 'garissa township', 'ward' => 'waberi', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'garissa township', 'ward' => 'galbet', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'garissa township', 'ward' => 'township', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'garissa township', 'ward' => 'iftin', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'balambala', 'ward' => 'balambala', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'balambala', 'ward' => 'danyere', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'balambala', 'ward' => 'jara jara', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'balambala', 'ward' => 'saka', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'balambala', 'ward' => 'sankuri', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'modogashe', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'benane', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'goreale', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'maalimin', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'sabena', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'lagdera', 'ward' => 'baraki', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'dertu', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'dadaab', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'labasigale', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'damajale', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'liboi', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'dadaab', 'ward' => 'abakaile', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'fafi', 'ward' => 'bura', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'fafi', 'ward' => 'dekaharia', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'fafi', 'ward' => 'jarajila', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'fafi', 'ward' => 'fafi', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'fafi', 'ward' => 'nanighi', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'ijara', 'ward' => 'hulugho', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'ijara', 'ward' => 'sangailu', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'ijara', 'ward' => 'ijara', 'alias' => ''],
            ['county_id' => 7, 'constituency_name' => 'ijara', 'ward' => 'masalani', 'alias' => ''],
            
            // Wajir County (8)
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'gurar', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'bute', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'korondile', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'malkagufu', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'batalu', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'danaba', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir north', 'ward' => 'godoma', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir east', 'ward' => 'wagberi', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir east', 'ward' => 'township', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir east', 'ward' => 'barwago', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir east', 'ward' => 'khorof/harar', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'tarbaj', 'ward' => 'elben', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'tarbaj', 'ward' => 'sarman', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'tarbaj', 'ward' => 'tarbaj', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'tarbaj', 'ward' => 'wargadud', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir west', 'ward' => 'arbajahan', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir west', 'ward' => 'hadado/athibohol', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir west', 'ward' => 'ademasajide', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir west', 'ward' => 'wagalla/ganyure', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'eldas', 'ward' => 'eldas', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'eldas', 'ward' => 'della', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'eldas', 'ward' => 'lakoley south/basir', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'eldas', 'ward' => 'elnur/tula tula', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'benane', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'burder', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'dadaja bulla', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'habasswein', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'lagboghol south', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'ibrahim ure', 'alias' => ''],
            ['county_id' => 8, 'constituency_name' => 'wajir south', 'ward' => 'diif', 'alias' => ''],
            
            // Mandera County (9)
            ['county_id' => 9, 'constituency_name' => 'mandera west', 'ward' => 'takaba south', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera west', 'ward' => 'takaba', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera west', 'ward' => 'lag sure', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera west', 'ward' => 'dandu', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera west', 'ward' => 'gither', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'banissa', 'ward' => 'banissa', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'banissa', 'ward' => 'derkhale', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'banissa', 'ward' => 'guba', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'banissa', 'ward' => 'malkamari', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'banissa', 'ward' => 'kiliwehiri', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera north', 'ward' => 'ashabito', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera north', 'ward' => 'guticha', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera north', 'ward' => 'morothile', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera north', 'ward' => 'rhamu', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera north', 'ward' => 'rhamu-dimtu', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera south', 'ward' => 'wargudud', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera south', 'ward' => 'kutulo', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera south', 'ward' => 'elwak south', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera south', 'ward' => 'elwak north', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera south', 'ward' => 'shimbir fatuma', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera east', 'ward' => 'arabia', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera east', 'ward' => 'bulla mpya', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera east', 'ward' => 'khalalio', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera east', 'ward' => 'neboi', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'mandera east', 'ward' => 'township', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'lafey', 'ward' => 'libehia', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'lafey', 'ward' => 'fino', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'lafey', 'ward' => 'lafey', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'lafey', 'ward' => 'warankara', 'alias' => ''],
            ['county_id' => 9, 'constituency_name' => 'lafey', 'ward' => 'alungo gof', 'alias' => ''],
            
            // Marsabit County (10)
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'butiye', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'sololo', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'heilu-manyatta', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'golbo', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'moyale township', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'uran', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'moyale', 'ward' => 'obbu', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'north horr', 'ward' => 'illeret', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'north horr', 'ward' => 'north horr', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'north horr', 'ward' => 'dukana', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'north horr', 'ward' => 'maikona', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'north horr', 'ward' => 'turbi', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'saku', 'ward' => 'sagante/jaldesa', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'saku', 'ward' => 'karare', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'saku', 'ward' => 'marsabit central', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'laisamis', 'ward' => 'loiyangalani', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'laisamis', 'ward' => 'kargi/south horr', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'laisamis', 'ward' => 'korr/ngurunit', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'laisamis', 'ward' => 'log logo', 'alias' => ''],
            ['county_id' => 10, 'constituency_name' => 'laisamis', 'ward' => 'laisamis', 'alias' => ''],
            
            // Isiolo County (11)
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'wabera', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'bulla pesa', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'chari', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'cherab', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'ngare mara', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'burat', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo north', 'ward' => 'oldonyiro', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo south', 'ward' => 'garbatulla', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo south', 'ward' => 'kinna', 'alias' => ''],
            ['county_id' => 11, 'constituency_name' => 'isiolo south', 'ward' => 'sericho', 'alias' => ''],
            
            // Meru County (12)
            ['county_id' => 12, 'constituency_name' => 'igembe south', 'ward' => 'maua', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe south', 'ward' => 'kiegoi/antubochiu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe south', 'ward' => 'athiru gaiti', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe south', 'ward' => 'akachiu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe south', 'ward' => 'kanuni', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe central', 'ward' => 'akirang\'ondu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe central', 'ward' => 'athiru ruujine', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe central', 'ward' => 'igembe east', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe central', 'ward' => 'njia', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe central', 'ward' => 'kangeta', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe north', 'ward' => 'antuambui', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe north', 'ward' => 'ntunene', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe north', 'ward' => 'antubetwe kiongo', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe north', 'ward' => 'naathu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'igembe north', 'ward' => 'amwathi', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania west', 'ward' => 'athwana', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania west', 'ward' => 'akithii', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania west', 'ward' => 'kianjai', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania west', 'ward' => 'nkomo', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania west', 'ward' => 'mbeu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania east', 'ward' => 'thangatha', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania east', 'ward' => 'mikinduri', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania east', 'ward' => 'kiguchwa', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania east', 'ward' => 'muthara', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'tigania east', 'ward' => 'karama', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'north imenti', 'ward' => 'municipality', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'north imenti', 'ward' => 'ntima east', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'north imenti', 'ward' => 'ntima west', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'north imenti', 'ward' => 'nyaki west', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'north imenti', 'ward' => 'nyaki east', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'buuri', 'ward' => 'timau', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'buuri', 'ward' => 'kisima', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'buuri', 'ward' => 'kiirua/naari', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'buuri', 'ward' => 'ruiri/rwarera', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'buuri', 'ward' => 'kibirichia', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'central imenti', 'ward' => 'mwanganthia', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'central imenti', 'ward' => 'abothuguchi central', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'central imenti', 'ward' => 'abothuguchi west', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'central imenti', 'ward' => 'kiagu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'mitunguu', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'igoji east', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'igoji west', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'abogeta east', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'abogeta west', 'alias' => ''],
            ['county_id' => 12, 'constituency_name' => 'south imenti', 'ward' => 'nkuene', 'alias' => ''],
            
            // Tharaka-Nithi County (13)
            ['county_id' => 13, 'constituency_name' => 'maara', 'ward' => 'mitheru', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'maara', 'ward' => 'muthambi', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'maara', 'ward' => 'mwimbi', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'maara', 'ward' => 'ganga', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'maara', 'ward' => 'chogoria', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'chuka/igambang\'om', 'ward' => 'mariani', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'chuka/igambang\'om', 'ward' => 'karingani', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'chuka/igambang\'om', 'ward' => 'magumoni', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'chuka/igambang\'om', 'ward' => 'mugwe', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'chuka/igambang\'om', 'ward' => 'igambang\'ombe', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'tharaka', 'ward' => 'gatunga', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'tharaka', 'ward' => 'mukothima', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'tharaka', 'ward' => 'nkondi', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'tharaka', 'ward' => 'chiakariga', 'alias' => ''],
            ['county_id' => 13, 'constituency_name' => 'tharaka', 'ward' => 'marimanti', 'alias' => ''],
            
            // Embu County (14)
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'ruguru/ngandori', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'kithimu', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'nginda', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'mbeti north', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'kirimari', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'manyatta', 'ward' => 'gaturi south', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'gaturi north', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'kagaari south', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'central ward', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'kagaari north', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'kyeni north', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'runyenjes', 'ward' => 'kyeni south', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere south', 'ward' => 'mwea', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere south', 'ward' => 'makima', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere south', 'ward' => 'mbeti south', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere south', 'ward' => 'mavuria', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere south', 'ward' => 'kiambere', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere north', 'ward' => 'nthawa', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere north', 'ward' => 'muminji', 'alias' => ''],
            ['county_id' => 14, 'constituency_name' => 'mbeere north', 'ward' => 'evurore', 'alias' => ''],
            
            // Kitui County (15)
            ['county_id' => 15, 'constituency_name' => 'mwingi north', 'ward' => 'ngomeni', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi north', 'ward' => 'kyuso', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi north', 'ward' => 'mumoni', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi north', 'ward' => 'tseikuru', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi north', 'ward' => 'tharaka', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi west', 'ward' => 'kyome/thaana', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi west', 'ward' => 'nguutani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi west', 'ward' => 'migwani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi west', 'ward' => 'kiomo/kyethani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'central', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'kivou', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'nguni', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'nuu', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'mui', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'mwingi central', 'ward' => 'waita', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui west', 'ward' => 'mutonguni', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui west', 'ward' => 'kauwi', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui west', 'ward' => 'matinyani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui west', 'ward' => 'kwa mutonga/kithumula', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui rural', 'ward' => 'kisasi', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui rural', 'ward' => 'mbitini', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui rural', 'ward' => 'kwavonza/yatta', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui rural', 'ward' => 'kanyangi', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui central', 'ward' => 'miambani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui central', 'ward' => 'township', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui central', 'ward' => 'kyangwithya west', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui central', 'ward' => 'mulango', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui central', 'ward' => 'kyangwithya east', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'zombe/mwitika', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'chuluni', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'nzambani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'voo/kyamatu', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'endau/malalani', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui east', 'ward' => 'mutito/kaliku', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'ikanga/kyatune', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'mutomo', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'mutha', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'ikutha', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'kanziko', 'alias' => ''],
            ['county_id' => 15, 'constituency_name' => 'kitui south', 'ward' => 'athi', 'alias' => ''],
            
            // Machakos County (16)
            ['county_id' => 16, 'constituency_name' => 'masinga', 'ward' => 'kivaa', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'masinga', 'ward' => 'masinga central', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'masinga', 'ward' => 'ekalakala', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'masinga', 'ward' => 'muthesya', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'masinga', 'ward' => 'ndithini', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'yatta', 'ward' => 'ndalani', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'yatta', 'ward' => 'matuu', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'yatta', 'ward' => 'kithimani', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'yatta', 'ward' => 'ikombe', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'yatta', 'ward' => 'katangi', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kangundo', 'ward' => 'kangundo north', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kangundo', 'ward' => 'kangundo central', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kangundo', 'ward' => 'kangundo east', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kangundo', 'ward' => 'kangundo west', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'matungulu', 'ward' => 'tala', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'matungulu', 'ward' => 'matungulu north', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'matungulu', 'ward' => 'matungulu east', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'matungulu', 'ward' => 'matungulu west', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'matungulu', 'ward' => 'kyeleni', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kathiani', 'ward' => 'mitaboni', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kathiani', 'ward' => 'kathiani central', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kathiani', 'ward' => 'upper kaewa/iveti', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'kathiani', 'ward' => 'lower kaewa/kaani', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mavoko', 'ward' => 'athi river', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mavoko', 'ward' => 'kinanie', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mavoko', 'ward' => 'muthwani', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mavoko', 'ward' => 'syokimau/mulolongo', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'kalama', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'mua', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'mutituni', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'machakos central', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'mumbuni north', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'muvuti/kiima-kimwe', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'machakos town', 'ward' => 'kola', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'mbiuni', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'makutano/ mwala', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'masii', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'muthetheni', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'wamunyu', 'alias' => ''],
            ['county_id' => 16, 'constituency_name' => 'mwala', 'ward' => 'kibauni', 'alias' => ''],
            
            // Makueni County (17)
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'tulimani', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'mbooni', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'kithungo/kitundu', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'kisau/kiteta', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'waia/kako', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'mbooni', 'ward' => 'kalawa', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kilome', 'ward' => 'kasikeu', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kilome', 'ward' => 'mukaa', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kilome', 'ward' => 'kiima kiu/kalanzoni', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kaiti', 'ward' => 'ukia', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kaiti', 'ward' => 'kee', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kaiti', 'ward' => 'kilungu', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'kaiti', 'ward' => 'ilima', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'makueni', 'ward' => 'wote', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'makueni', 'ward' => 'muvau/kikuumini', 'alias' => ''],
            ['county_id' => 17, 'constituency_name' => 'makueni', 'ward' => 'mavindini', 'alias' => ''],
            
            // Nyandarua County (18)
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'engineer', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'gathara', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'north kinangop', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'murungaru', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'njabini/kiburu', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'nyakio', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'githabai', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kinangop', 'ward' => 'magumu', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kipipiri', 'ward' => 'wanjohi', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kipipiri', 'ward' => 'kipipiri', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kipipiri', 'ward' => 'geta', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'kipipiri', 'ward' => 'githioro', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol kalou', 'ward' => 'karau', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol kalou', 'ward' => 'kanjuiri ridge', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol kalou', 'ward' => 'mirangine', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol kalou', 'ward' => 'kaimbaga', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol kalou', 'ward' => 'rurii', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol jorok', 'ward' => 'gathanji', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol jorok', 'ward' => 'gatimu', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol jorok', 'ward' => 'weru', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ol jorok', 'ward' => 'charagita', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ndaragwa', 'ward' => 'leshau pondo', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ndaragwa', 'ward' => 'kiriita', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ndaragwa', 'ward' => 'central', 'alias' => 'none'],
            ['county_id' => 18, 'constituency_name' => 'ndaragwa', 'ward' => 'shamata', 'alias' => 'none'],

            // Nyeri County (19)
            ['county_id' => 19, 'constituency_name' => 'tetu', 'ward' => 'dedan kimanthi', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'tetu', 'ward' => 'wamagana', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'tetu', 'ward' => 'aguthi/gaaki', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'mweiga', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'naromoru kiamathaga', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'mwiyogo/endarasha', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'mugunda', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'gatarakwa', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'thegu river', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'kabaru', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'kieni', 'ward' => 'gakawa', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'ruguru', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'magutu', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'iriaini', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'konyu', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'kirimukuyu', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mathira', 'ward' => 'karatina town', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'othaya', 'ward' => 'mahiga', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'othaya', 'ward' => 'iria-ini', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'othaya', 'ward' => 'chinga', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'othaya', 'ward' => 'karima', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mukurweini', 'ward' => 'gikondi', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mukurweini', 'ward' => 'rugi', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mukurweini', 'ward' => 'mukurwe-ini west', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'mukurweini', 'ward' => 'mukurwe-ini central', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'nyeri town', 'ward' => 'kiganjo/mathari', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'nyeri town', 'ward' => 'rware', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'nyeri town', 'ward' => 'gatitu/muruguru', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'nyeri town', 'ward' => 'ruring\'u', 'alias' => 'none'],
            ['county_id' => 19, 'constituency_name' => 'nyeri town', 'ward' => 'kamakwa/mukaro', 'alias' => 'none'],

            // Kirinyaga County (20)
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'mutithi', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'kangai', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'thiba', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'wamumu', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'nyangati', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'murinduko', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'gathigiriri', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'mwea', 'ward' => 'tebere', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'gichugu', 'ward' => 'kabare', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'gichugu', 'ward' => 'baragwi', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'gichugu', 'ward' => 'njukiini', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'gichugu', 'ward' => 'ngariama', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'gichugu', 'ward' => 'karumandi', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'ndia', 'ward' => 'mukure', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'ndia', 'ward' => 'kiine', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'ndia', 'ward' => 'kariti', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'kirinyaga central', 'ward' => 'mutira', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'kirinyaga central', 'ward' => 'kanyeki-ini', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'kirinyaga central', 'ward' => 'kerugoya', 'alias' => 'none'],
            ['county_id' => 20, 'constituency_name' => 'kirinyaga central', 'ward' => 'inoi', 'alias' => 'none'],

            // Murang'a County (21)
            ['county_id' => 21, 'constituency_name' => 'kangema', 'ward' => 'kanyenyaini', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kangema', 'ward' => 'muguru', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kangema', 'ward' => 'rwathia', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'mathioya', 'ward' => 'gitugi', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'mathioya', 'ward' => 'kiru', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'mathioya', 'ward' => 'kamacharia', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'wangu', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'mugoiri', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'mbiri', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'township', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'murarandia', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kiharu', 'ward' => 'gaturi', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kigumo', 'ward' => 'kahumbu', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kigumo', 'ward' => 'muthithi', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kigumo', 'ward' => 'kigumo', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kigumo', 'ward' => 'kangari', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kigumo', 'ward' => 'kinyona', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'kimorori/wempa', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'makuyu', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'kambiti', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'kamahuha', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'ichagaki', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'maragwa', 'ward' => 'nginda', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'ng\'araria', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'muruka', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'kagundu-ini', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'gaichanjiru', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'ithiru', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'kandara', 'ward' => 'ruchu', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'ithanga', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'kakuzi/mitubiri', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'mugumo-ini', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'kihumbu-ini', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'gatanga', 'alias' => 'none'],
            ['county_id' => 21, 'constituency_name' => 'gatanga', 'ward' => 'kariara', 'alias' => 'none'],

            // Kiambu County (22)
            ['county_id' => 22, 'constituency_name' => 'gatundu south', 'ward' => 'kiamwangi', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu south', 'ward' => 'kiganjo', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu south', 'ward' => 'ndarugu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu south', 'ward' => 'ngenda', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu north', 'ward' => 'gituamba', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu north', 'ward' => 'githobokoni', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu north', 'ward' => 'chania', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'gatundu north', 'ward' => 'mang\'u', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'juja', 'ward' => 'murera', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'juja', 'ward' => 'theta', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'juja', 'ward' => 'juja', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'juja', 'ward' => 'witeithie', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'juja', 'ward' => 'kalimoni', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'thika town', 'ward' => 'township', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'thika town', 'ward' => 'kamenu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'thika town', 'ward' => 'hospital', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'thika town', 'ward' => 'gatuanyaga', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'thika town', 'ward' => 'ngoliba', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'gitothua', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'biashara', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'gatongora', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'kahawa sukari', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'kahawa wendani', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'kiuu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'mwiki', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'ruiru', 'ward' => 'mwihoko', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'githunguri', 'ward' => 'githunguri', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'githunguri', 'ward' => 'githiga', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'githunguri', 'ward' => 'ikinu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'githunguri', 'ward' => 'ngewa', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'githunguri', 'ward' => 'komothai', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambu', 'ward' => 'ting\'ang\'a', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambu', 'ward' => 'ndumberi', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambu', 'ward' => 'riabai', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambu', 'ward' => 'township', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambaa', 'ward' => 'cianda', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambaa', 'ward' => 'karuri', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambaa', 'ward' => 'ndenderu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambaa', 'ward' => 'muchatha', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kiambaa', 'ward' => 'kihara', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kabete', 'ward' => 'gitaru', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kabete', 'ward' => 'muguga', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kabete', 'ward' => 'nyadhuna', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kabete', 'ward' => 'kabete', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kabete', 'ward' => 'uthiru', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kikuyu', 'ward' => 'karai', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kikuyu', 'ward' => 'nachu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kikuyu', 'ward' => 'sigona', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kikuyu', 'ward' => 'kikuyu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'kikuyu', 'ward' => 'kinoo', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'limuru', 'ward' => 'bibirioni', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'limuru', 'ward' => 'limuru central', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'limuru', 'ward' => 'ndeiya', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'limuru', 'ward' => 'limuru east', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'limuru', 'ward' => 'ngecha tigoni', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'lari', 'ward' => 'kinale', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'lari', 'ward' => 'kijabe', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'lari', 'ward' => 'nyanduma', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'lari', 'ward' => 'kamburu', 'alias' => 'none'],
            ['county_id' => 22, 'constituency_name' => 'lari', 'ward' => 'lari/kirenga', 'alias' => 'none'],

            // Turkana County (23)
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'kaeris', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'lake zone', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'lapur', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'kaaleng/kaikor', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'kibish', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana north', 'ward' => 'nakalale', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'kakuma', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'lopur', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'letea', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'songot', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'kalobeyei', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'lokichoggio', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana west', 'ward' => 'nanaam', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana central', 'ward' => 'kerio delta', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana central', 'ward' => 'kang\'atotha', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana central', 'ward' => 'kalokol', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana central', 'ward' => 'lodwar township', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana central', 'ward' => 'kanamkemer', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'loima', 'ward' => 'kotaruk/lobei', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'loima', 'ward' => 'turkwel', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'loima', 'ward' => 'loima', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'loima', 'ward' => 'lokiriama/lorengippi', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana south', 'ward' => 'kaputir', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana south', 'ward' => 'katilu', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana south', 'ward' => 'lobokat', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana south', 'ward' => 'kalapata', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana south', 'ward' => 'lokichar', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana east', 'ward' => 'kapedo/napeitom', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana east', 'ward' => 'katilia', 'alias' => 'none'],
            ['county_id' => 23, 'constituency_name' => 'turkana east', 'ward' => 'lokori/kochodin', 'alias' => 'none'],

            // West Pokot County (24)
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'riwo', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'kapenguria', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'mnagei', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'siyoi', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'endugh', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kapenguria', 'ward' => 'sook', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'sigor', 'ward' => 'sekerr', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'sigor', 'ward' => 'masool', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'sigor', 'ward' => 'lomut', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'sigor', 'ward' => 'weiwei', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'suam', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'kodich', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'kapckok', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'kasei', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'kiwawa', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'kacheliba', 'ward' => 'alale', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'pokot south', 'ward' => 'chepareria', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'pokot south', 'ward' => 'batei', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'pokot south', 'ward' => 'lelan', 'alias' => 'none'],
            ['county_id' => 24, 'constituency_name' => 'pokot south', 'ward' => 'tapach', 'alias' => 'none'],

            // Samburu County (25)
            ['county_id' => 25, 'constituency_name' => 'samburu west', 'ward' => 'lodokejek', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu west', 'ward' => 'suguta marmar', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu west', 'ward' => 'maralal', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu west', 'ward' => 'loosuk', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu west', 'ward' => 'poro', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'el-barta', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'nachola', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'ndoto', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'nyiro', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'angata nanyokie', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu north', 'ward' => 'baawa', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu east', 'ward' => 'waso', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu east', 'ward' => 'wamba west', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu east', 'ward' => 'wamba east', 'alias' => 'none'],
            ['county_id' => 25, 'constituency_name' => 'samburu east', 'ward' => 'wamba north', 'alias' => 'none'],

            // Trans Nzoia County (26)
            ['county_id' => 26, 'constituency_name' => 'kwanza', 'ward' => 'kapomboi', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kwanza', 'ward' => 'kwanza', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kwanza', 'ward' => 'keiyo', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kwanza', 'ward' => 'bidii', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'endebess', 'ward' => 'chepchoina', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'endebess', 'ward' => 'endebess', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'endebess', 'ward' => 'matumbei', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'saboti', 'ward' => 'kinyoro', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'saboti', 'ward' => 'matisi', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'saboti', 'ward' => 'tuwani', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'saboti', 'ward' => 'saboti', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'saboti', 'ward' => 'machewa', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'kiminini', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'waitaluk', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'sirende', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'hospital', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'sikhendu', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'kiminini', 'ward' => 'nabiswa', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'sinyerere', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'makutano', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'kaplamai', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'motosiet', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'cherangany/suwerwa', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'chepsiro/kiptoror', 'alias' => 'none'],
            ['county_id' => 26, 'constituency_name' => 'cherangany', 'ward' => 'sitatunga', 'alias' => 'none'],

            // Uasin Gishu County (27)
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'moi\'s bridge', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'kapkures', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'ziwa', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'segero/barsombe', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'kipsomba', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'soy', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'soy', 'ward' => 'kuinet/kapsuswa', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'ngenyilel', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'tapsagoi', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'kamagut', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'kiplombe', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'kapsaos', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'turbo', 'ward' => 'huruma', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'moiben', 'ward' => 'tembelio', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'moiben', 'ward' => 'sergoit', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'moiben', 'ward' => 'karuna/meibeki', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'moiben', 'ward' => 'moiben', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'moiben', 'ward' => 'kimumu', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'ainabkoi', 'ward' => 'kapsoya', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'ainabkoi', 'ward' => 'kaptagat', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'ainabkoi', 'ward' => 'ainabkoi/olare', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kapseret', 'ward' => 'simat/kapseret', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kapseret', 'ward' => 'kipkenyo', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kapseret', 'ward' => 'ngeria', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kapseret', 'ward' => 'megun', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kapseret', 'ward' => 'langas', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kesses', 'ward' => 'racecourse', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kesses', 'ward' => 'cheptiret/kipchamo', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kesses', 'ward' => 'tulwet/chuiyat', 'alias' => 'none'],
            ['county_id' => 27, 'constituency_name' => 'kesses', 'ward' => 'tarakwa', 'alias' => 'none'],

            // Elgeyo-Marakwet County (28)
            ['county_id' => 28, 'constituency_name' => 'marakwet east', 'ward' => 'kapyego', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet east', 'ward' => 'sambirir', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet east', 'ward' => 'endo', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet east', 'ward' => 'embobut / embulot', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'lelan', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'sengwer', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'cherang\'any/chebororwa', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'moiben/kuserwo', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'kapsowar', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'marakwet west', 'ward' => 'arror', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo north', 'ward' => 'emsoo', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo north', 'ward' => 'kamariny', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo north', 'ward' => 'kapchemutwa', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo north', 'ward' => 'tambach', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'kaptarakwa', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'chepkorio', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'soy north', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'soy south', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'kabiemit', 'alias' => 'none'],
            ['county_id' => 28, 'constituency_name' => 'keiyo south', 'ward' => 'metkei', 'alias' => 'none'],

            // Nandi County (29)
            ['county_id' => 29, 'constituency_name' => 'tinderet', 'ward' => 'songhor/soba', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'tinderet', 'ward' => 'tindiret', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'tinderet', 'ward' => 'chemelil/chemase', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'tinderet', 'ward' => 'kapsimotwo', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'kabwareng', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'terik', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'kemeloi-maraba', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'kobujoi', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'kaptumo-kaboi', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'aldai', 'ward' => 'koyo-ndurio', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'nandi hills', 'ward' => 'nandi hills', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'nandi hills', 'ward' => 'chepkunyuk', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'nandi hills', 'ward' => 'ol\'lessos', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'nandi hills', 'ward' => 'kapchorua', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'chesumei', 'ward' => 'chemundu/kapng\'etuny', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'chesumei', 'ward' => 'kosirai', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'chesumei', 'ward' => 'lelmokwo/ngechek', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'chesumei', 'ward' => 'kaptel/kamoiywo', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'chesumei', 'ward' => 'kiptuya', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'emgwen', 'ward' => 'chepkumia', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'emgwen', 'ward' => 'kapkangani', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'emgwen', 'ward' => 'kapsabet', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'emgwen', 'ward' => 'kilibwoni', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'chepterwai', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'kipkaren', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'kurgung/surungai', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'kabiyet', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'ndalat', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'kabisaga', 'alias' => 'none'],
            ['county_id' => 29, 'constituency_name' => 'mosop', 'ward' => 'sangalo/kebulonik', 'alias' => 'none'],

            // Baringo County (30)
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'tirioko', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'kolowa', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'ribkwo', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'silale', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'loiyamorock', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'tangulbei/korossi', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'tiaty', 'ward' => 'churo/amaya', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo north', 'ward' => 'barwessa', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo north', 'ward' => 'kabartonjo', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo north', 'ward' => 'saimo/kipsaraman', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo north', 'ward' => 'saimo/soi', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo north', 'ward' => 'bartabwa', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo central', 'ward' => 'kabarnet', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo central', 'ward' => 'sacho', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo central', 'ward' => 'tenges', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo central', 'ward' => 'ewalel chapchap', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo central', 'ward' => 'kapropita', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo south', 'ward' => 'marigat', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo south', 'ward' => 'ilchamus', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo south', 'ward' => 'mochongoi', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'baringo south', 'ward' => 'mukutani', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'mogotio', 'ward' => 'mogotio', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'mogotio', 'ward' => 'emining', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'mogotio', 'ward' => 'kisanana', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'lembus', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'lembus kwen', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'ravine', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'mumberes/maji mazuri', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'lembus/perkerra', 'alias' => 'none'],
            ['county_id' => 30, 'constituency_name' => 'eldama ravine', 'ward' => 'koibatek', 'alias' => 'none'],

            // Laikipia County (31)
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'olmoran', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'rumuruti township', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'kinamba', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'marmanet', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'igwamiti', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia west', 'ward' => 'salama', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia east', 'ward' => 'ngobit', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia east', 'ward' => 'tigithi', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia east', 'ward' => 'thingithu', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia east', 'ward' => 'nanyuki', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia east', 'ward' => 'umande', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia north', 'ward' => 'sosian', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia north', 'ward' => 'segera', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia north', 'ward' => 'mukogondo west', 'alias' => 'none'],
            ['county_id' => 31, 'constituency_name' => 'laikipia north', 'ward' => 'mukogondo east', 'alias' => 'none'],
       ];

        // Truncate the table first
        SubCounty::truncate();
        
        // Process in chunks to avoid memory issues
        foreach (array_chunk($subCounties, 100) as $chunk) {
            SubCounty::insert($chunk);
        }
    }
}
